enum MsolStatusCodes {
    MSOL_INPUT_INVALID = "MSOL_INPUT_INVALID",
    MSOL_SNS_CREATED = "MSOL_SNS_CREATED",
    MSOL_SNS_FOUND = "MSOL_SNS_FOUND",
    MSOL_SNS_NOT_FOUND = "MSOL_SNS_NOT_FOUND",
    MSOL_SOMETHING_WENT_WRONG = "MSOL_SOMETHING_WENT_WRONG",
    MSOL_SNS_EXISTS = "MSOL_SNS_EXISTS"
}

const HttpResponseCode = {
    SUCCESS: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
};

export {
    HttpResponseCode,
    MsolStatusCodes
}